version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - apupier
  - bfitzpat
  - lhein
- package-ecosystem: maven
  directory: "/wsdl2rest"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
